export default {
	title: "Магомед Вагабов",
	description:
		"Мультидисциплинарный дизайнер с научным бэкграундом. Могу закодить статичный сайт, сверстать плотный постер и обсчитать статистику. Люблю типографику, сложные системы и визуализацию данных.",
	shortdescription: "",
	url: "https://magvag.ru",
	language: "ru",
	blog_homepage: "/notes/",
	blog_homepage_name: "vagabov magazine",
	navigation_pages: [
		{
			title: "магомед вагабов",
			url: "/",
			tag: "me",
			type: "mecard",
			pos: 0,
			width: 24,
			nav_items: [
				{ name: "телега", url: "https://t.me/magvag/" },
				{ name: "канал", url: "https://t.me/magmoyed/" },
			],
		},
		{
			title: "vagabov magazine",
			url: "/notes/",
			tag: "posts",
			type: "blogcard",
			pos: 28,
			width: 20,
			// style: "mix-blend-mode: darken;",
			nav_items: [
				{ name: "шрифты", tag: "шрифты" },
				{ name: "юикс", tag: "UX" },
				{ name: "история", tag: "история" },
				{ name: "знаки", tag: "символы" },
				{ name: "датавиз", tag: "инфографика" },
				{ name: "вёрстка", tag: "вёрстка" },
				{ name: "техносреда", tag: "техносреда" },
			],
		},
		{
			title: "Раскладка для биологов",
			url: "/layout/",
			tag: "layout",
			pos: 52,
			width: 80,
			nav_items: [
				{ name: "проект", url: "/layout/" },
				{ name: "вопросы", url: "/layout/faq/" },
				{ name: "постер", url: "/layout/poster/" },
				{ name: "символы", url: "/layout/symbols/" },
			],
			// style: "mix-blend-mode: darken;",
		},
		{
			title: "Шрифт для биофака МГУ",
			url: "/mihey/",
			tag: "mihey",
			pos: 136,
			width: 100,
			disabled: true,
		},
		{
			title: "Трирема — сетап для блога",
			url: "/trireme/",
			tag: "trireme",
			pos: 240,
			width: 80,
			disabled: true,
			// style: "mix-blend-mode: darken;",
		},
		{
			title: "Редизайн Биоуниверсиады",
			url: "/universiade/",
			tag: "universiade",
			pos: 324,
			width: 80,
			disabled: true,
			// style: "mix-blend-mode: darken;",
		},
	],
	blog_foundation: "2025",
	author: {
		name: "Магомед Вагабов",
		email: "inbox@magvag.ru",
		url: "https://magvag.ru",
	},
	tag_links: [
		{ name: "шрифты", url: "fonts" },
		{ name: "инфографика", url: "dataviz" },
		{ name: "вёрстка", url: "layout-design" },
		{ name: "техносреда", url: "advanced-PC-user" },
		{ name: "символы", url: "symbols" },
		{ name: "UX", url: "UX" },
		{ name: "Раскладка для биологов", url: "biolayout" },
		{ name: "история", url: "history" },
	],
};
