export default {
	title: "Магомед Вагабов",
	description:
		"Мультидисциплинарный дизайнер с научным бэкграундом. Могу закодить статичный сайт, сверстать плотный— постер и обсчитать статистику. Люблю типографику, сложные системы и визуализацию данных.",
	shortdescription: "",
	url: "https://magvag.ru",
	language: "ru",
	blog_homepage: "/notes/",
	blog_homepage_name: "vagabov magazine",
	navigation_pages: [
		{
			title: "Раскладка для биологов",
			url: "/layout/",
			tag: "layout",
			pos: 43,
			width: 80,
		},
		{
			title: "Шрифт для биофака МГУ",
			url: "/mihey/",
			tag: "mihey",
			pos: 123,
			width: 99,
			disabled: true,
		},
		{
			title: "Трирема — сетап для блога",
			url: "/trireme/",
			tag: "trireme",
			pos: 222,
			width: 80,
			disabled: true,
		},
		{
			title: "Редизайн Биоуниверсиады",
			url: "/universiade/",
			tag: "universiade",
			pos: 303,
			width: 76,
			disabled: true,
			style: "mix-blend-mode: darken;",
		},
	],
	blog_foundation: "2025",
	author: {
		name: "Магомед Вагабов",
		email: "inbox@magvag.ru",
		url: "https://magvag.ru",
	},
	tag_links: [
		{ name: "фичи", url: "features" },
		{ name: "навигация", url: "navigation" },
		{ name: "оптимизация", url: "optimization" },
	],
};
